# Generated by Django 5.1.4 on 2024-12-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Utilities', 'Utilities'), ('Health', 'Health'), ('Education', 'Education'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='expense',
            name='note',
            field=models.TextField(blank=True, default='An Expense', max_length=50),
        ),
    ]
