# Generated by Django 5.1.4 on 2024-12-17 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTracker', '0002_rename_name_expense_title_expense_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('title', 'category', 'note', 'price', 'date')},
        ),
    ]
