# Generated by Django 5.1.4 on 2024-12-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTracker', '0005_alter_expense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
    ]
